import { BROKERS } from "./authorizedAccounts.js";

export const BROKER_ADS = [
  {
    id: "headway",
    broker: "Headway",
    partnerId: "516d6b",
    active: true,
    expiryDate: null, // Ongoing promo
    badge: "🔥 Free $150 Bonus",
    headline: "Claim $150 No-Deposit Trading Bonus at Headway",
    shortHeadline: "Headway $150 No-Deposit Trading Bonus",
    desc: "Trade 5 markets for 7 days with zero capital risk. Test EA Budak Ubat risk-free and keep your profits!",
    shortDesc: "Get $150 free credit to trade 5 markets for 7 days with zero risk. Whitelist your account & test our EAs!",
    cta: "Claim $150 Bonus ➜",
    url: "https://headway.partners/landings/en/bonus-150/?hwp=516d6b",
    image: "/banners/headway-banner.png",
    imageAlt: "Headway Bonus $150 - 7 Days. 5 Markets. 0 Risk",
    accentColor: "#f59e0b",
    glowColor: "rgba(245, 158, 11, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(245, 158, 11, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(217, 119, 6, 0.08) 100%)",
    borderColor: "rgba(245, 158, 11, 0.32)",
    btnGradient: "linear-gradient(135deg, #f59e0b, #d97706)",
    btnColor: "#0a0e1a",
  },
  {
    id: "fbs",
    broker: "FBS",
    partnerId: "588292",
    active: true,
    expiryDate: null,
    badge: "⚡ 0.01s Execution · 1:3000 Leverage",
    headline: "Be Smart. Trade Smart with FBS Broker",
    shortHeadline: "FBS Broker — High-Speed EA Execution",
    desc: "Ultra-fast execution from 0.01s, spreads from 0.7 pips & leverage up to 1:3000. Officially recommended for MT4 & MT5 EAs!",
    shortDesc: "Ultra-fast 0.01s execution, spreads from 0.7 pips & leverage up to 1:3000. Ideal for Grid & Trend EAs!",
    cta: "Trade with FBS ➜",
    url: "https://fbs.partners?ibl=154319&ibp=588292",
    image: "/banners/fbs-banner.jpg",
    imageAlt: "Be Smart. Trade Smart with FBS Broker",
    accentColor: "#00be40",
    glowColor: "rgba(0, 190, 64, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(0, 190, 64, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(5, 150, 105, 0.08) 100%)",
    borderColor: "rgba(0, 190, 64, 0.32)",
    btnGradient: "linear-gradient(135deg, #00be40, #059669)",
    btnColor: "#ffffff",
  },
  {
    id: "xm",
    broker: "XM",
    partnerId: "HVVR7",
    active: true,
    expiryDate: null,
    badge: "🎁 100% Deposit Bonus",
    headline: "Get a 100% Deposit Bonus with XM",
    shortHeadline: "XM 100% Deposit Bonus",
    desc: "Instantly increase your trading power with a 100% deposit bonus. Trade Gold, global shares, indices, and forex pairs with zero requotes!",
    shortDesc: "100% deposit bonus on your trading capital. Trade global equities, FX, and Gold with XM.",
    cta: "Trade Now at XM ➜",
    url: "https://clicks.pipaffiliates.com/c?m=150422&c=862266",
    image: "/banners/xm-banner.png",
    imageAlt: "XM 100% Deposit Bonus",
    accentColor: "#ef4444",
    glowColor: "rgba(239, 68, 68, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(239, 68, 68, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(185, 28, 28, 0.08) 100%)",
    borderColor: "rgba(239, 68, 68, 0.32)",
    btnGradient: "linear-gradient(135deg, #ef4444, #dc2626)",
    btnColor: "#ffffff",
  },
  {
    id: "tickmill",
    broker: "Tickmill",
    partnerId: "IB72324388",
    active: true,
    expiryDate: null,
    badge: "🪙 Trade Gold Lowest Spreads",
    headline: "Trade the World's Most Precious Metal with Tickmill",
    shortHeadline: "Tickmill Trade Gold Lowest Spreads",
    desc: "Trade Gold with the lowest spreads and lightning-fast execution on live Tickmill servers. Perfect for automated EAs!",
    shortDesc: "Trade Gold with the lowest raw spreads. Institutional execution tailored for automated trading.",
    cta: "Trade Gold at Tickmill ➜",
    url: "https://tickmill.link/46cOQ2h",
    image: "/banners/tickmill-banner.jpg",
    imageAlt: "Tickmill Trade Gold Lowest Spreads",
    accentColor: "#e11d48",
    glowColor: "rgba(225, 29, 72, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(225, 29, 72, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(159, 18, 57, 0.08) 100%)",
    borderColor: "rgba(225, 29, 72, 0.32)",
    btnGradient: "linear-gradient(135deg, #e11d48, #be123c)",
    btnColor: "#ffffff",
  },
  {
    id: "hfm",
    broker: "HF Markets",
    partnerId: "30572923",
    active: true,
    expiryDate: null,
    badge: "🛡️ Official Arsenal FC Partner",
    headline: "Keep More of Every Trade with HF Markets",
    shortHeadline: "HF Markets 0.0 Pips Spreads",
    desc: "Lower your trading costs with competitive pricing and spreads from 0.0 pips with a broker trusted by millions.",
    shortDesc: "Lower trading costs with spreads from 0.0 pips. Official partner of Arsenal FC trusted by millions.",
    cta: "Join HF Markets ➜",
    url: "https://www.hfmmalaysia.com/sv/en/?refid=30572923",
    image: "/banners/hfm-banner.jpg",
    imageAlt: "HF Markets 20% Top-Up Bonus",
    accentColor: "#f43f5e",
    glowColor: "rgba(244, 63, 94, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(244, 63, 94, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(190, 18, 60, 0.08) 100%)",
    borderColor: "rgba(244, 63, 94, 0.32)",
    btnGradient: "linear-gradient(135deg, #f43f5e, #e11d48)",
    btnColor: "#ffffff",
  },
  {
    id: "roboforex",
    broker: "RoboForex",
    partnerId: "mxyg",
    active: true,
    expiryDate: null,
    badge: "🪙 $30 Welcome Bonus",
    headline: "Welcome Bonus 30 USD with RoboForex / R Infinity",
    shortHeadline: "RoboForex 30 USD Welcome Bonus",
    desc: "Register and receive initial funds for trading. Welcome Bonus funds aren't written off from your account even during drawdown. Withdraw all profits!",
    shortDesc: "Receive 30 USD initial funds for trading. Funds stay in your account during drawdown. Full profit withdrawals.",
    cta: "Get 30 USD Bonus ➜",
    url: "https://rinfinity.com/en/welcome-bonus?a=mxyg",
    image: "/banners/roboforex-banner.png",
    imageAlt: "RoboForex R Infinity 30 USD Welcome Bonus",
    accentColor: "#3b82f6",
    glowColor: "rgba(59, 130, 246, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(59, 130, 246, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(29, 78, 216, 0.08) 100%)",
    borderColor: "rgba(59, 130, 246, 0.32)",
    btnGradient: "linear-gradient(135deg, #3b82f6, #2563eb)",
    btnColor: "#ffffff",
  },
  {
    id: "justmarkets",
    broker: "JustMarkets",
    partnerId: "tjrtn60m2i",
    active: true,
    expiryDate: null,
    badge: "💎 Full Trading Potential",
    headline: "Reach Your Full Trading Potential with JustMarkets",
    shortHeadline: "JustMarkets Trading Potential",
    desc: "Trade gold, oil, indices, and crypto with confidence. Competitive pricing, zero requotes, and instant execution.",
    shortDesc: "Trade gold, oil, and FX with top-tier conditions. Instant order execution and tight spreads for EAs.",
    cta: "Start with JustMarkets ➜",
    url: "https://one.justmarkets.link/a/tjrtn60m2i",
    image: "/banners/justmarkets-banner.jpg",
    imageAlt: "JustMarkets 120% Deposit Bonus",
    accentColor: "#0ea5e9",
    glowColor: "rgba(14, 165, 233, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(14, 165, 233, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(3, 105, 161, 0.08) 100%)",
    borderColor: "rgba(14, 165, 233, 0.32)",
    btnGradient: "linear-gradient(135deg, #0ea5e9, #0284c7)",
    btnColor: "#ffffff",
  },
  {
    id: "litefinance",
    broker: "LiteFinance",
    partnerId: "805161060",
    active: true,
    expiryDate: null,
    badge: "🎉 100% Deposit Match",
    headline: "Double Your Deposit with 100% LiteFinance Bonus",
    shortHeadline: "LiteFinance 100% Deposit Match",
    desc: "Double your margin power with 100% deposit bonus. Supports micro cent accounts starting from $10 with automated copy-trading.",
    shortDesc: "100% deposit match bonus + Cent accounts from $10. Trade EA Budak Ubat with maximum resilience.",
    cta: "Double My Deposit ➜",
    url: "https://www.litefinance.com/?uid=805161060",
    image: "/banners/litefinance-banner.jpg",
    imageAlt: "LiteFinance 100% Deposit Match",
    accentColor: "#14b8a6",
    glowColor: "rgba(20, 184, 166, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(20, 184, 166, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(15, 118, 110, 0.08) 100%)",
    borderColor: "rgba(20, 184, 166, 0.32)",
    btnGradient: "linear-gradient(135deg, #14b8a6, #0d9488)",
    btnColor: "#ffffff",
  },
  {
    id: "instaforex",
    broker: "InstaForex",
    partnerId: "KUSD",
    active: true,
    expiryDate: null,
    badge: "🛡️ 100% First Deposit Bonus",
    headline: "Claim 100% First Deposit Bonus with InstaForex",
    shortHeadline: "InstaForex 100% Deposit Bonus",
    desc: "Get a 100% bonus on your first deposit to trade currency pairs, commodities, and gold with fixed or floating spreads.",
    shortDesc: "100% bonus on initial deposit. Trade with an established broker featuring 300+ financial assets.",
    cta: "Claim 100% at InstaForex ➜",
    url: "https://www.instaforex.com?x=KUSD",
    image: "/banners/instaforex-banner.jpg",
    imageAlt: "InstaForex 100% First Deposit Bonus",
    accentColor: "#ef4444",
    glowColor: "rgba(239, 68, 68, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(239, 68, 68, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(185, 28, 28, 0.08) 100%)",
    borderColor: "rgba(239, 68, 68, 0.32)",
    btnGradient: "linear-gradient(135deg, #ef4444, #dc2626)",
    btnColor: "#ffffff",
  },
  {
    id: "markets4you",
    broker: "Markets4you",
    partnerId: "4hcnvz4",
    active: true,
    expiryDate: null,
    badge: "💰 Up to 40% Spread Cashback",
    headline: "Get More Value From Every Trade at Markets4you",
    shortHeadline: "Markets4you 40% Cashback",
    desc: "Earn up to 40% cashback on paid spreads and commissions with no time limit. Cent accounts from $10 with 19 years track record!",
    shortDesc: "Up to 40% spread cashback with no time limit. Cent accounts from $10 with automated EA rebates.",
    cta: "Get Spread Cashback ➜",
    url: "https://account.markets4you.online/en/user-registration/?affid=4hcnvz4",
    image: "/banners/markets4you-banner.jpg",
    imageAlt: "Markets4you 100% Bonus and Rebates",
    accentColor: "#10b981",
    glowColor: "rgba(16, 185, 129, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(16, 185, 129, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(4, 120, 87, 0.08) 100%)",
    borderColor: "rgba(16, 185, 129, 0.32)",
    btnGradient: "linear-gradient(135deg, #10b981, #059669)",
    btnColor: "#0a0e1a",
  },
  {
    id: "cxm",
    broker: "CXM Direct",
    partnerId: "5062",
    active: true,
    expiryDate: null,
    badge: "🔥 100% Tradable Credit",
    headline: "100% Tradable Credit Bonus at CXM Direct",
    shortHeadline: "CXM Direct 100% Tradable Bonus",
    desc: "Tradable credit bonus that withstands drawdowns. Cent accounts available with deep institutional liquidity.",
    shortDesc: "Tradable bonus protects equity during market retracements. Ideal for grid martingale EA layering.",
    cta: "Claim CXM Bonus ➜",
    url: "https://gocxm.co/links/go/5062",
    image: "/banners/cxm-banner.png",
    imageAlt: "CXM Direct 100% Tradable Credit",
    accentColor: "#a855f7",
    glowColor: "rgba(168, 85, 247, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(168, 85, 247, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(126, 34, 206, 0.08) 100%)",
    borderColor: "rgba(168, 85, 247, 0.32)",
    btnGradient: "linear-gradient(135deg, #a855f7, #9333ea)",
    btnColor: "#ffffff",
  },
  {
    id: "valetax",
    broker: "Valetax",
    partnerId: "1939088",
    active: true,
    expiryDate: null,
    badge: "⚡ A Better Way To Trade",
    headline: "Trade with 0.0 Pip Spreads & 1:500 Leverage at Valetax",
    shortHeadline: "Valetax 0.0 Pip Spreads",
    desc: "Enjoy 0.0 pip spreads, 1:500 leverage, 0.01 micro lot trading, and over 1,750 tradable instruments.",
    shortDesc: "0.0 pip spreads, 1:500 leverage, and 0.01 micro lot trading across 1,750+ instruments.",
    cta: "Open Valetax Account ➜",
    url: "https://ma.valetax.com/p/1939088",
    image: "/banners/valetax-banner.png",
    imageAlt: "Valetax 100% Deposit Match",
    accentColor: "#6366f1",
    glowColor: "rgba(99, 102, 241, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(99, 102, 241, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(67, 56, 202, 0.08) 100%)",
    borderColor: "rgba(99, 102, 241, 0.32)",
    btnGradient: "linear-gradient(135deg, #6366f1, #4f46e5)",
    btnColor: "#ffffff",
  },
  {
    id: "eightcap",
    broker: "Eightcap",
    partnerId: "8660",
    active: true,
    expiryDate: null,
    badge: "🏆 Trade Gold 24/7",
    headline: "Trade Gold CFDs All Day, Every Day with Eightcap GOLD247",
    shortHeadline: "Eightcap GOLD247 Trading",
    desc: "Access Gold/USD CFD trading 24 hours a day, 7 days a week with GOLD247 from an award-winning regulated broker.",
    shortDesc: "24/7 Gold CFD trading with award-winning ultra-low raw spreads from 0.0 pips.",
    cta: "Trade Gold with Eightcap ➜",
    url: "https://partners.eightcap.com/click?campaign_id=1&ref_id=8660",
    image: "/banners/eightcap-banner.png",
    imageAlt: "Eightcap 0.0 Pips Raw Spread",
    accentColor: "#059669",
    glowColor: "rgba(5, 150, 105, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(5, 150, 105, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(4, 120, 87, 0.08) 100%)",
    borderColor: "rgba(5, 150, 105, 0.32)",
    btnGradient: "linear-gradient(135deg, #059669, #047857)",
    btnColor: "#ffffff",
  },
  {
    id: "fisg",
    broker: "FISG",
    partnerId: "CTt0Rd",
    active: true,
    expiryDate: null,
    badge: "⭐ Speed · Precision · Agility",
    headline: "Master the Moment with FISG & Andrés Iniesta",
    shortHeadline: "FISG Master the Moment",
    desc: "Official brand ambassador Andrés Iniesta. Direct institutional liquidity, ultra-fast execution, and zero hidden markups.",
    shortDesc: "Direct tier-1 institutional liquidity with lightning-fast execution and zero hidden markups.",
    cta: "Open FISG Account ➜",
    url: "https://my.fisg.com/u/CTt0Rd",
    image: "/banners/fisg-banner.png",
    imageAlt: "FISG Institutional Raw ECN",
    accentColor: "#f59e0b",
    glowColor: "rgba(245, 158, 11, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(245, 158, 11, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(180, 83, 9, 0.08) 100%)",
    borderColor: "rgba(245, 158, 11, 0.32)",
    btnGradient: "linear-gradient(135deg, #f59e0b, #d97706)",
    btnColor: "#0a0e1a",
  },
];

/**
 * Filter out inactive or expired ads, and automatically synthesize
 * an ad for any newly added broker in BROKERS that doesn't yet have a custom ad entry.
 */
export function getActiveAds() {
  const today = new Date().toISOString().split("T")[0];
  const activeCustomAds = BROKER_ADS.filter((ad) => {
    if (!ad.active) return false;
    if (ad.expiryDate && ad.expiryDate < today) return false;
    return true;
  });

  // Check for any broker in BROKERS not yet configured in BROKER_ADS
  const configuredBrokerNames = new Set(
    BROKER_ADS.map((a) => a.broker.toLowerCase().replace(/[^a-z0-9]/g, ""))
  );

  const autoGeneratedAds = (BROKERS || [])
    .filter((b) => {
      const normalized = b.name.toLowerCase().replace(/[^a-z0-9]/g, "");
      return !configuredBrokerNames.has(normalized);
    })
    .map((b) => {
      const slug = b.name.toLowerCase().replace(/[^a-z0-9]/g, "-");
      return {
        id: slug,
        broker: b.name,
        partnerId: b.id,
        active: true,
        expiryDate: null,
        badge: "🏛️ Official Partner Broker",
        headline: `Trade with ${b.name} & Get Free EA Whitelist`,
        shortHeadline: `${b.name} Official Partner Access`,
        desc: `Open a live trading account with ${b.name} (Partner Code: ${b.id}) to enjoy permanent free access to EA Budak Ubat MT4 & MT5!`,
        shortDesc: `Register using partner code ${b.id} for instant whitelist access to all our Expert Advisors.`,
        cta: `Register with ${b.name} ➜`,
        url: b.url,
        image: `/banners/default-banner.svg`,
        imageAlt: `${b.name} Partner Registration`,
        accentColor: "#3b82f6",
        glowColor: "rgba(59, 130, 246, 0.22)",
        bgGradient: "linear-gradient(135deg, rgba(59, 130, 246, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(37, 99, 235, 0.08) 100%)",
        borderColor: "rgba(59, 130, 246, 0.32)",
        btnGradient: "linear-gradient(135deg, #3b82f6, #2563eb)",
        btnColor: "#ffffff",
      };
    });

  return [...activeCustomAds, ...autoGeneratedAds];
}

