// Centralized Broker Promotional Ads & Banners Configuration
// Used by RotatingAdBanner across the website (Homepage, Account Checker, Product pages)

export const BROKER_ADS = [
  {
    id: "headway",
    broker: "Headway",
    partnerId: "516d6b",
    active: true,
    expiryDate: null, // Ongoing promo
    badge: "🔥 Free $150 Bonus",
    headline: "Claim $150 No-Deposit Trading Bonus at Headway",
    shortHeadline: "Headway $150 No-Deposit Trading Bonus",
    desc: "Trade 5 markets for 7 days with zero capital risk. Test EA Budak Ubat risk-free and keep your profits!",
    shortDesc: "Get $150 free credit to trade 5 markets for 7 days with zero risk. Whitelist your account & test our EAs!",
    cta: "Claim $150 Bonus ➜",
    url: "https://headway.partners/landings/en/bonus-150/?hwp=516d6b",
    image: "/banners/headway-banner.png",
    imageAlt: "Headway Bonus $150 - 7 Days. 5 Markets. 0 Risk",
    accentColor: "#f59e0b",
    glowColor: "rgba(245, 158, 11, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(245, 158, 11, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(217, 119, 6, 0.08) 100%)",
    borderColor: "rgba(245, 158, 11, 0.32)",
    btnGradient: "linear-gradient(135deg, #f59e0b, #d97706)",
    btnColor: "#0a0e1a",
  },
  {
    id: "fbs",
    broker: "FBS",
    partnerId: "588292",
    active: true,
    expiryDate: null,
    badge: "⚡ 0.01s Execution · 1:3000 Leverage",
    headline: "Be Smart. Trade Smart with FBS Broker",
    shortHeadline: "FBS Broker — High-Speed EA Execution",
    desc: "Ultra-fast execution from 0.01s, spreads from 0.7 pips & leverage up to 1:3000. Officially recommended for MT4 & MT5 EAs!",
    shortDesc: "Ultra-fast 0.01s execution, spreads from 0.7 pips & leverage up to 1:3000. Ideal for Grid & Trend EAs!",
    cta: "Trade with FBS ➜",
    url: "https://fbs.partners?ibl=154319&ibp=588292",
    image: "/banners/fbs-banner.jpg",
    imageAlt: "Be Smart. Trade Smart with FBS Broker",
    accentColor: "#00be40",
    glowColor: "rgba(0, 190, 64, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(0, 190, 64, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(5, 150, 105, 0.08) 100%)",
    borderColor: "rgba(0, 190, 64, 0.32)",
    btnGradient: "linear-gradient(135deg, #00be40, #059669)",
    btnColor: "#ffffff",
  },
  {
    id: "xm",
    broker: "XM",
    partnerId: "HVVR7",
    active: true,
    expiryDate: null,
    badge: "🎁 $30 Free Trading Bonus",
    headline: "Get $30 No-Deposit Trading Bonus with XM",
    shortHeadline: "XM $30 Free Trading Bonus",
    desc: "No deposit required. Open a real XM account, receive $30 instant trading credit, and withdraw all profits made!",
    shortDesc: "Start trading with $30 free balance. No deposit needed, all profits withdrawable. Fully compatible with our EAs!",
    cta: "Claim $30 at XM ➜",
    url: "https://clicks.pipaffiliates.com/c?c=862266&l=en&p=1",
    image: "/banners/xm-banner.svg",
    imageAlt: "XM $30 Free Trading Bonus",
    accentColor: "#ef4444",
    glowColor: "rgba(239, 68, 68, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(239, 68, 68, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(185, 28, 28, 0.08) 100%)",
    borderColor: "rgba(239, 68, 68, 0.32)",
    btnGradient: "linear-gradient(135deg, #ef4444, #dc2626)",
    btnColor: "#ffffff",
  },
  {
    id: "tickmill",
    broker: "Tickmill",
    partnerId: "IB72324388",
    active: true,
    expiryDate: null,
    badge: "⚡ $30 Welcome Account",
    headline: "Claim $30 Free Welcome Account at Tickmill",
    shortHeadline: "Tickmill $30 Welcome Account",
    desc: "Experience ultra-low raw spreads from 0.0 pips and lightning-fast execution. Zero financial commitment!",
    shortDesc: "Trade on live Tickmill servers with $30 gifted trading capital. Raw spreads from 0.0 pips for automated EAs.",
    cta: "Open Welcome Account ➜",
    url: "https://tickmill.link/46cOQ2h",
    image: "/banners/tickmill-banner.svg",
    imageAlt: "Tickmill $30 Welcome Account",
    accentColor: "#e11d48",
    glowColor: "rgba(225, 29, 72, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(225, 29, 72, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(159, 18, 57, 0.08) 100%)",
    borderColor: "rgba(225, 29, 72, 0.32)",
    btnGradient: "linear-gradient(135deg, #e11d48, #be123c)",
    btnColor: "#ffffff",
  },
  {
    id: "hfm",
    broker: "HF Markets",
    partnerId: "30572923",
    active: true,
    expiryDate: null,
    badge: "🚀 20% Top-Up Bonus",
    headline: "Boost Your Balance with HF Markets 20% Bonus",
    shortHeadline: "HF Markets 20% Top-Up Bonus",
    desc: "Earn an extra 20% on every deposit up to $5,000. Low spreads, 1:2000 leverage, and fast local bank deposits.",
    shortDesc: "Extra 20% margin buffer on all deposits. Perfect for martingale grid survival and higher lot flexibility.",
    cta: "Get HF Markets Bonus ➜",
    url: "https://www.hfmmalaysia.com/sv/en/?refid=30572923",
    image: "/banners/hfm-banner.svg",
    imageAlt: "HF Markets 20% Top-Up Bonus",
    accentColor: "#f43f5e",
    glowColor: "rgba(244, 63, 94, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(244, 63, 94, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(190, 18, 60, 0.08) 100%)",
    borderColor: "rgba(244, 63, 94, 0.32)",
    btnGradient: "linear-gradient(135deg, #f43f5e, #e11d48)",
    btnColor: "#ffffff",
  },
  {
    id: "roboforex",
    broker: "RoboForex",
    partnerId: "mxyg",
    active: true,
    expiryDate: null,
    badge: "🪙 $30 Welcome Bonus",
    headline: "Claim $30 Welcome Bonus at RoboForex",
    shortHeadline: "RoboForex $30 Welcome Bonus",
    desc: "Deposit just $10 and receive an extra $30 initial funds with maximum leverage up to 1:2000. Cent accounts supported!",
    shortDesc: "Start with $30 welcome bonus + 1:2000 leverage. Cent & Pro accounts specifically designed for EA trading.",
    cta: "Claim $30 Bonus ➜",
    url: "https://my.roboforex.com/en/?a=mxyg",
    image: "/banners/roboforex-banner.svg",
    imageAlt: "RoboForex $30 Welcome Bonus",
    accentColor: "#3b82f6",
    glowColor: "rgba(59, 130, 246, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(59, 130, 246, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(29, 78, 216, 0.08) 100%)",
    borderColor: "rgba(59, 130, 246, 0.32)",
    btnGradient: "linear-gradient(135deg, #3b82f6, #2563eb)",
    btnColor: "#ffffff",
  },
  {
    id: "justmarkets",
    broker: "JustMarkets",
    partnerId: "tjrtn60m2i",
    active: true,
    expiryDate: null,
    badge: "💎 Up to 120% Bonus",
    headline: "Receive up to 120% First Deposit Bonus at JustMarkets",
    shortHeadline: "JustMarkets 120% Deposit Bonus",
    desc: "Multiply your capital with tiered deposit bonuses up to 120%. Tight spreads, zero requotes, and instant FPX deposits.",
    shortDesc: "Multiply your trading balance by up to 120% on your first deposit. Superior order execution for EAs.",
    cta: "Claim 120% Bonus ➜",
    url: "https://one.justmarkets.link/a/tjrtn60m2i",
    image: "/banners/justmarkets-banner.svg",
    imageAlt: "JustMarkets 120% Deposit Bonus",
    accentColor: "#0ea5e9",
    glowColor: "rgba(14, 165, 233, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(14, 165, 233, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(3, 105, 161, 0.08) 100%)",
    borderColor: "rgba(14, 165, 233, 0.32)",
    btnGradient: "linear-gradient(135deg, #0ea5e9, #0284c7)",
    btnColor: "#ffffff",
  },
  {
    id: "litefinance",
    broker: "LiteFinance",
    partnerId: "805161060",
    active: true,
    expiryDate: null,
    badge: "🎉 100% Deposit Match",
    headline: "Double Your Deposit with 100% LiteFinance Bonus",
    shortHeadline: "LiteFinance 100% Deposit Match",
    desc: "Double your margin power with 100% deposit bonus. Supports micro cent accounts starting from $10 with automated copy-trading.",
    shortDesc: "100% deposit match bonus + Cent accounts from $10. Trade EA Budak Ubat with maximum resilience.",
    cta: "Double My Deposit ➜",
    url: "https://www.litefinance.com/?uid=805161060",
    image: "/banners/litefinance-banner.svg",
    imageAlt: "LiteFinance 100% Deposit Match",
    accentColor: "#14b8a6",
    glowColor: "rgba(20, 184, 166, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(20, 184, 166, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(15, 118, 110, 0.08) 100%)",
    borderColor: "rgba(20, 184, 166, 0.32)",
    btnGradient: "linear-gradient(135deg, #14b8a6, #0d9488)",
    btnColor: "#ffffff",
  },
  {
    id: "instaforex",
    broker: "InstaForex",
    partnerId: "KUSD",
    active: true,
    expiryDate: null,
    badge: "🛡️ 100% First Deposit Bonus",
    headline: "Claim 100% First Deposit Bonus with InstaForex",
    shortHeadline: "InstaForex 100% Deposit Bonus",
    desc: "Get a 100% bonus on your first deposit to trade currency pairs, commodities, and gold with fixed or floating spreads.",
    shortDesc: "100% bonus on initial deposit. Trade with an established broker featuring 300+ financial assets.",
    cta: "Claim 100% at InstaForex ➜",
    url: "https://www.instaforex.com?x=KUSD",
    image: "/banners/instaforex-banner.svg",
    imageAlt: "InstaForex 100% First Deposit Bonus",
    accentColor: "#ef4444",
    glowColor: "rgba(239, 68, 68, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(239, 68, 68, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(185, 28, 28, 0.08) 100%)",
    borderColor: "rgba(239, 68, 68, 0.32)",
    btnGradient: "linear-gradient(135deg, #ef4444, #dc2626)",
    btnColor: "#ffffff",
  },
  {
    id: "markets4you",
    broker: "Markets4you",
    partnerId: "4hcnvz4",
    active: true,
    expiryDate: null,
    badge: "💰 100% Bonus + 50% Rebates",
    headline: "100% Deposit Bonus & 50% Rebates at Markets4you",
    shortHeadline: "Markets4you 100% Bonus & Rebates",
    desc: "Cent accounts from $10, 100% deposit bonus, plus automated daily rebates back into your trading wallet.",
    shortDesc: "Cent accounts from $10 with 100% deposit bonus and 50% automated spread cashbacks directly to your balance.",
    cta: "Register Markets4you ➜",
    url: "https://account.markets4you.online/en/user-registration/?affid=4hcnvz4",
    image: "/banners/markets4you-banner.svg",
    imageAlt: "Markets4you 100% Bonus and Rebates",
    accentColor: "#10b981",
    glowColor: "rgba(16, 185, 129, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(16, 185, 129, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(4, 120, 87, 0.08) 100%)",
    borderColor: "rgba(16, 185, 129, 0.32)",
    btnGradient: "linear-gradient(135deg, #10b981, #059669)",
    btnColor: "#0a0e1a",
  },
  {
    id: "cxm",
    broker: "CXM Direct",
    partnerId: "5062",
    active: true,
    expiryDate: null,
    badge: "🔥 100% Tradable Credit",
    headline: "100% Tradable Credit Bonus at CXM Direct",
    shortHeadline: "CXM Direct 100% Tradable Bonus",
    desc: "Tradable credit bonus that withstands drawdowns. Cent accounts available with deep institutional liquidity.",
    shortDesc: "Tradable bonus protects equity during market retracements. Ideal for grid martingale EA layering.",
    cta: "Claim CXM Bonus ➜",
    url: "https://gocxm.co/links/go/5062",
    image: "/banners/cxm-banner.svg",
    imageAlt: "CXM Direct 100% Tradable Credit",
    accentColor: "#a855f7",
    glowColor: "rgba(168, 85, 247, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(168, 85, 247, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(126, 34, 206, 0.08) 100%)",
    borderColor: "rgba(168, 85, 247, 0.32)",
    btnGradient: "linear-gradient(135deg, #a855f7, #9333ea)",
    btnColor: "#ffffff",
  },
  {
    id: "valetax",
    broker: "Valetax",
    partnerId: "1939088",
    active: true,
    expiryDate: null,
    badge: "⚡ 100% Deposit Match",
    headline: "100% Deposit Match & High Leverage with Valetax",
    shortHeadline: "Valetax 100% Deposit Match",
    desc: "Enjoy zero swap accounts, instant crypto funding, and high leverage execution tailored for modern automated strategies.",
    shortDesc: "Instant crypto & FPX funding with 100% deposit match. Zero-swap trading environment for multi-day EA positions.",
    cta: "Open Valetax Account ➜",
    url: "https://ma.valetax.com/p/1939088",
    image: "/banners/valetax-banner.svg",
    imageAlt: "Valetax 100% Deposit Match",
    accentColor: "#6366f1",
    glowColor: "rgba(99, 102, 241, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(99, 102, 241, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(67, 56, 202, 0.08) 100%)",
    borderColor: "rgba(99, 102, 241, 0.32)",
    btnGradient: "linear-gradient(135deg, #6366f1, #4f46e5)",
    btnColor: "#ffffff",
  },
  {
    id: "eightcap",
    broker: "Eightcap",
    partnerId: "8660",
    active: true,
    expiryDate: null,
    badge: "🏆 0.0 Pips Raw Spread",
    headline: "Trade on Raw Spreads from 0.0 Pips with Eightcap",
    shortHeadline: "Eightcap Raw Spreads from 0.0 Pips",
    desc: "Award-winning ASIC & SCB regulated broker. Equinix NY4 server infrastructure ensures sub-millisecond execution for EAs.",
    shortDesc: "Award-winning ultra-low raw spreads from 0.0 pips. Exceptional execution reliability for EA Budak Ubat MT4/MT5.",
    cta: "Trade with Eightcap ➜",
    url: "https://partners.eightcap.com/click?campaign_id=1&ref_id=8660",
    image: "/banners/eightcap-banner.svg",
    imageAlt: "Eightcap 0.0 Pips Raw Spread",
    accentColor: "#059669",
    glowColor: "rgba(5, 150, 105, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(5, 150, 105, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(4, 120, 87, 0.08) 100%)",
    borderColor: "rgba(5, 150, 105, 0.32)",
    btnGradient: "linear-gradient(135deg, #059669, #047857)",
    btnColor: "#ffffff",
  },
  {
    id: "fisg",
    broker: "FISG",
    partnerId: "CTt0Rd",
    active: true,
    expiryDate: null,
    badge: "🏛️ Institutional ECN",
    headline: "Institutional Raw ECN & Zero Commission with FISG",
    shortHeadline: "FISG Institutional Raw ECN",
    desc: "Direct market access to tier-1 liquidity providers. Zero commission accounts and customized VPS solutions.",
    shortDesc: "Tier-1 institutional liquidity with raw spreads and zero hidden markups. Optimized for heavy algorithmic trading.",
    cta: "Open FISG Account ➜",
    url: "https://my.fisg.com/u/CTt0Rd",
    image: "/banners/fisg-banner.svg",
    imageAlt: "FISG Institutional Raw ECN",
    accentColor: "#f59e0b",
    glowColor: "rgba(245, 158, 11, 0.22)",
    bgGradient: "linear-gradient(135deg, rgba(245, 158, 11, 0.12) 0%, rgba(17, 24, 39, 0.88) 50%, rgba(180, 83, 9, 0.08) 100%)",
    borderColor: "rgba(245, 158, 11, 0.32)",
    btnGradient: "linear-gradient(135deg, #f59e0b, #d97706)",
    btnColor: "#0a0e1a",
  },
];

/**
 * Filter out inactive or expired ads
 */
export function getActiveAds() {
  const today = new Date().toISOString().split("T")[0];
  return BROKER_ADS.filter((ad) => {
    if (!ad.active) return false;
    if (ad.expiryDate && ad.expiryDate < today) return false;
    return true;
  });
}
